#!/bin/sh

lock() {
  i3lock -c 000000 -p win -d
}

_suspend() {
  dbus-send \
    --system \
    --dest=org.freedesktop.UPower \
    --type=method_call \
    --print-reply \
    /org/freedesktop/UPower \
    org.freedesktop.UPower.Suspend
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    lock && _suspend
    ;;
  hibernate)
    lock && systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
esac
exit 0
