# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
  output_format = "i3bar"
  colors = true
  interval = 1
  color_good = "#0099CC"
  color_bad = "#FF0066"
  color_separator = "#000000"
}

order += "cpu_usage"
order += "load"
order += "disk /"
order += "ethernet eth0"
order += "wireless wlan0"
order += "battery 0"
order += "tztime local"
order += "volume master"

cpu_usage {
  format = "cpu at %usage"
}

cpu_temperature 0 {
  format = "T: %degrees °C"
  path = "/sys/devices/platform/coretemp.0/temp1_input"
}


wireless wlan0 {
  format_up = "wlan %ip on %essid"
  format_down = "wlan"
}

ethernet eth0 {
  # if you use %speed, i3status requires root privileges
  format_up = "eth %ip"
  format_down = "eth"
  color_bad = "#777777"
}

battery 0 {
  format = "%status %percentage %remaining"
}

run_watch DHCP {
  pidfile = "/var/run/dhclient*.pid"
}

run_watch VPN {
  pidfile = "/var/run/vpnc/pid"
}

load {
  format = "load %1min"
}

disk "/" {
  format = "%avail free"
}

battery 0 {
  format = "%status %percentage %remaining"
}

tztime local {
  format = "%Y-%m-%d %H:%M:%S %Z"
}

volume master {
  format = "♪: %volume"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}
