# This tmux statusbar config was created by tmuxline.vim
# on Mon, 20 Jan 2014

set -g message-style fg=colour7,bg=colour11
set -g message-command-style bg=colour11,fg=colour7
set -g pane-active-border-style fg=colour14
set -g pane-border-style fg=colour11
set -g status 'on'
set -g status-justify 'centre'
set -g status-left '#{prefix_highlight}#[fg=colour7,bg=colour14,nobold] #h::#[fg=colour7,bg=colour14,bold]#S '
set -g status-left-length '100'
set -g status-right '#[fg=colour7,bg=colour11] %D %H:%M prodaccess:#{prodaccess_status}'
set -g status-right-length '100'
set -g status-style bg=colour0
setw -g window-status-activity-style bg=colour0,fg=colour14
setw -g window-status-style bg=colour0,fg=colour10
setw -g window-status-current-format '#[fg=colour7,bg=colour11] #I:#W*#P '
setw -g window-status-format '#[fg=colour10,bg=colour8] #I:#W '
setw -g window-status-separator ' '
