"
" Vim Config
" Matthew Ziegelbaum
"

" Preconfig for Vundle
set nocompatible               " be iMproved

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

let mapleader = ","
let maplocalleader = "\\"

call plug#begin('~/.vim/plugged')

"Navigation
Plug 'kien/ctrlp.vim'
Plug 'JazzCore/ctrlp-cmatcher'
Plug 'Lokaltog/vim-easymotion'

" UI
Plug 'bling/vim-airline'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tomtom/quickfixsigns_vim'
Plug 'altercation/vim-colors-solarized'
Plug 'ervandew/supertab'
Plug 'edkolev/tmuxline.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'edkolev/promptline.vim'

" Commands
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-fugitive'
Plug 'godlygeek/tabular', { 'on': ['Tab', 'Tabularize'] }
Plug 'gmarik/sudo-gui.vim', { 'on': ['SudoWrite', 'W'] }
Plug 'milkypostman/vim-togglelist'
Plug 'mutewinter/swap-parameters'
Plug 'keepcase.vim'
Plug 'scratch.vim', { 'on': 'Scratch' }
Plug 'sjbach/lusty'
Plug 'benmills/vimux'
Plug 'rking/ag.vim'

" JS
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'jelera/vim-javascript-syntax', { 'for': 'javascript' }
Plug 'othree/javascript-libraries-syntax.vim', { 'for': 'javascript' }
Plug 'leshill/vim-json'
Plug 'itspriddle/vim-jquery', { 'for': 'javascript' }
Plug 'marijnh/tern_for_vim', { 'for': 'javascript' }

" Random languages
Plug 'Raimondi/delimitMate'
Plug 'Blackrush/vim-gocode', { 'for': 'go' }
Plug 'ChrisYip/Better-CSS-Syntax-for-Vim', { 'for': 'css' }
Plug 'acustodioo/vim-tmux'
Plug 'hallison/vim-markdown', { 'for': 'markdown' }
Plug 'scrooloose/syntastic'
Plug 'tfnico/vim-gradle'
Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }
Plug 'mattn/emmet-vim', { 'for': ['html', 'xml', 'haml', 'xsl', 'xslt']}
Plug 'ingydotnet/yaml-vim', { 'for': 'yaml' }

call plug#end()

syntax on
silent! source ~/.vimrc-pre

if has('gui_running')
  set guioptions=aegirLt
endif

if has('gui_macvim')
  if has("gui_running")
    set guioptions=egmrt
  endif
  set macmeta
endif

colorscheme solarized

set backup
set backupdir=~/.vim/backup//
set directory=~/.vim/tmp//
set undodir=~/.vim/tmp/undo//
set noswapfile

set ruler
set nu
set nowrap
set laststatus=2
set cmdheight=2
set encoding=utf-8
if exists("+colorcolumn")
  set colorcolumn=+1
endif

syntax on
set autoread
set wildmenu
set hidden
set history=768
set cf
set autowrite
au FocusLost * :wa

set tabstop=2
set backspace=2
set shiftwidth=2
set cindent
set autoindent
set smarttab
set expandtab

nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set incsearch
set hlsearch
set gdefault
set wildignore+=*.o,*.obj,*.exe,*.so,*.dll,*.pyc,.svn,.hg,.bzr,.git,
  \.sass-cache,*.class,*.scssc,*.cssc,sprockets%*,*.lessc
set sidescrolloff=2
set numberwidth=4
nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

set showmatch
set matchtime=2

set equalalways
set splitbelow splitright
:noremap ,v <C-w>v<C-w>l
:noremap ,h <C-w>s<C-w>j

set cursorline
set relativenumber
set undofile

set list

" Reset the listchars
set listchars=""
" a tab should display as "  ", trailing whitespace as "."
set listchars=tab:▸\·,eol:¬,trail:\·,extends:»,precedes:«
highlight NonText ctermfg=DarkGrey
highlight SpecialKey ctermbg=0 ctermfg=DarkRed
" Demo: tab & trailing spaces should be red	text    

set noerrorbells
set novisualbell
set t_vb=

" set mousehide
set mouse=a

set complete=.,w,b,u,U

command! W w
command! Q q

" ---------------
" Window movement
" ---------------
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" ---------------
" Turn off the arrows
" ---------------
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
" Move by visual line, not file line
nnoremap j gj
nnoremap k gk



nmap <C-d> <C-b>
if has("gui_macvim")
  nmap <D-f> <C-f>
  nmap <D-d> <C-b>
else
  nmap <M-f> <C-f>
  nmap <M-d> <C-b>
endif

nmap gy :%y+<cr> " Yank entire buffer


" ---------------
" NERDTree
" ---------------
nnoremap <leader>nn :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=2 " Change the NERDTree directory to the root node
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType")
  \&& b:NERDTreeType == "primary") | q | endif

"----------------
" YankRing
" ---------------
nnoremap <silent> <F3> :YRShow<cr>
inoremap <silent> <F3> <ESC>:YRShow<cr>
let g:yankring_replace_n_pkey = '<M-p>'
let g:yankring_replace_n_nkey = '<M-n>'

" ---------------
" Session
" ---------------
let g:session_autosave=0
let g:session_autoload=0
nnoremap <leader>os :OpenSession<CR>

" ---------------
" SpeedDating
" ---------------
let g:speeddating_no_mappings=1 " Remove default mappings (C-a etc.)
nmap <silent><leader>dm <Plug>SpeedDatingDown
nmap <silent><leader>dp <Plug>SpeedDatingUp
nmap <silent><leader>dn <Plug>SpeedDatingNowUTC

" ---------------
" Tabular
" ---------------
nmap <Leader>t= :Tabularize /=<CR>
vmap <Leader>t= :Tabularize /=<CR>
nmap <Leader>t: :Tabularize /:\zs<CR>
vmap <Leader>t: :Tabularize /:\zs<CR>
nmap <Leader>t, :Tabularize /,\zs<CR>
vmap <Leader>t, :Tabularize /,\zs<CR>
nmap <Leader>t> :Tabularize /=>\zs<CR>
vmap <Leader>t> :Tabularize /=>\zs<CR>
nmap <Leader>t- :Tabularize /-<CR>
vmap <Leader>t- :Tabularize /-<CR>
nmap <Leader>t" :Tabularize /"<CR>
vmap <Leader>t" :Tabularize /"<CR>

" ---------------
" Fugitive
" ---------------
nmap <Leader>gc :Gcommit -v<CR>
nmap <Leader>gw :Gwrite<CR>
nmap <Leader>gs :Gstatus<CR>
nmap <Leader>gp :Git push<CR>
 " Mnemonic, gu = Git Update
nmap <Leader>gu :Git pull<CR>
nmap <Leader>gd :Gdiff<CR>
" Exit a diff by closing the diff window
nmap <Leader>gx :wincmd h<CR>:q<CR>

" ---------------
" Zoomwin
" ---------------
" Zoom Window to Full Size
nmap <silent> <leader>wo :ZoomWin<CR>

" ---------------
" ctrlp.vim
" ---------------

" Ensure max height isn't too large.
let g:ctrlp_max_height = 10
let g:ctrl_cmd = 'CtrlPMixed'
let g:ctrlp_match_func = {'match' : 'matcher#cmatch' }
let g:ctrlp_working_path_mode = 'ra'

" ---------------
" Vundle
" ---------------
nmap <Leader>bi :BundleInstall<CR>
nmap <Leader>bu :BundleInstall!<CR> " Because this also updates
nmap <Leader>bc :BundleClean<CR>

" ---------------
" Strip Trailing White Space
" ---------------
" From http://vimbits.com/bits/377
" Preserves/Saves the state, executes a command, and returns to the saved state
function! Preserve(command)
  " Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
  " Do the business:
  execute a:command
  " Clean up: restore previous search history, and cursor position
  let @/=_s
  call cursor(l, c)
endfunction
"strip all trailing white space
command! StripTrailingWhiteSpace :call Preserve("%s/\\s\\+$//e")<CR>

imap jj <Esc>
imap uu _
imap hh =>
imap aa @

map <S-Enter> O<ESC>
map <Enter> o<ESC>
imap <C-c> <CR><Esc>O

" Key mappings " {{{
nnoremap <silent> <LocalLeader>rs :source ~/.vimrc<CR>
nnoremap <silent> <LocalLeader>rt :tabnew ~/.vim/vimrc<CR>
nnoremap <silent> <LocalLeader>re :e ~/.vim/vimrc<CR>
nnoremap <silent> <LocalLeader>rd :e ~/.vim/ <CR>

vmap so !sort<CR>
nmap <silent> <leader>w :w<CR>
nmap <silent> <leader>x :bd<CR>

nmap <silent> <Space> <PageDown>
nmap <silent> <M-Space> <PageUp>

nnoremap <leader>a :Ack

noremap  <F2> :NERDTreeToggle<cr>
inoremap <F2> <esc>:NERDTreeToggle<cr>

let g:airline_powerline_fonts = 1
let g:tmuxline_preset = 'crosshair'
let g:promptline_preset = {
        \'a': [ promptline#slices#user() ],
        \'b': [ promptline#slices#cwd() ],
        \'c' : [ promptline#slices#vcs_branch() ],
        \'warn' : [ promptline#slices#last_exit_code(), promptline#slices#battery() ],
        \'z' : [ promptline#slices#host() ]}


"au FileType javascript call JavaScriptFold()

" Post-config
silent! source ~/.vimrc-post

