#!/bin/bash
temp=$(sensors -A thinkpad-isa-0000 | grep CPU | awk '{print $2}' | sed -e 's/+//' -e 's/\.0//')
class="normal"
pct=$(echo $temp | sed -e 's/°C//')

if [[ $pct -gt 79 ]]; then
	class="warning"
elif [[ $pct -gt 99 ]]; then
	class="critical"
fi

echo "{\"text\": \"$temp\", \"tooltip\": \" ${temp}\", \"class\": \"$class\", \"percentage\": $pct }"

